import os
from typing import List, Dict, Any
from sentence_transformers import SentenceTransformer
from graph.state import AgentState, SynthesisResult, CritiqueResult, Chunk
from retrieval.qdrant_store import qdrant_store


class WriterAgent:
    """Formats synthesis into structured Markdown report. Stores to Qdrant memory."""
    
    def __init__(self):
        self.embedder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    
    def run(self, state: AgentState) -> str:
        if state.declined:
            return self._format_decline(state)
        
        return self._format_report(state)
    
    def _format_report(self, state: AgentState) -> str:
        synthesis = state.synthesis
        critique = state.critique
        
        lines = [
            f"# {state.research_question}",
            "",
            f"*Generated by InSyfy | Quality score: {critique.quality_score:.2f if critique else 'N/A'} | Sources: {len(state.search_results)}*",
            "",
            "## Executive Summary",
            ""
        ]
        
        # Executive summary from top 2-3 findings
        if synthesis and synthesis.key_findings:
            top_findings = sorted(
                synthesis.key_findings,
                key=lambda f: f.confidence,
                reverse=True
            )[:3]
            summary = "; ".join([f.claim for f in top_findings])
            lines.append(summary[:500])
        else:
            lines.append("No findings available.")
        
        lines.extend(["", "## Key Findings", ""])
        
        if synthesis:
            for i, finding in enumerate(synthesis.key_findings, 1):
                lines.append(f"### Finding {i}: {finding.claim}")
                lines.append(f"- Confidence: {finding.confidence:.2f}")
                if finding.supporting_chunks:
                    lines.append(f"- Supported by chunks: {', '.join(finding.supporting_chunks[:3])}")
                if finding.contradictions:
                    lines.append(f"- ⚠️ Contradictions: {'; '.join(finding.contradictions)}")
                lines.append("")
        
        # Limitations
        lines.extend(["## Evidence Gaps & Limitations", ""])
        if critique and critique.gap_analysis:
            lines.append(critique.gap_analysis)
        if state.quality_warning:
            lines.append("\n**Warning:** Quality threshold not met after maximum retries.")
        lines.append("")
        
        # Sources
        lines.extend(["## Sources", ""])
        citation_map = self._build_citation_map(state)
        for cid, info in sorted(citation_map.items()):
            lines.append(f"[^{cid}]: {info['title']} — {info['url']}")
        
        # Methodology
        lines.extend([
            "",
            "## Methodology",
            f"- Sub-queries searched: {len(state.plan.sub_queries) if state.plan else 0}",
            f"- Total chunks retrieved: {sum(len(r.chunks) for r in state.search_results) + len(state.rag_chunks)}",
            f"- Retrieval methods: web search + Qdrant hybrid (vector + keyword + cross-encoder rerank)",
            f"- Quality score: {critique.quality_score:.2f if critique else 'N/A'} (threshold: {state.plan.quality_threshold if state.plan else 'N/A'})",
            f"- Retry iterations: {state.retry_count}"
        ])
        
        report = "\n".join(lines)
        
        # Store to Qdrant memory
        self._store_to_memory(state, report)
        
        return report
    
    def _format_decline(self, state: AgentState) -> str:
        chunks_count = sum(len(r.chunks) for r in state.search_results) + len(state.rag_chunks)
        
        return f"""## Insufficient Evidence

InSyfy retrieved {chunks_count} chunks for this query, but none met the minimum evidence threshold.

**Question:** {state.research_question}

**Reason:** {state.decline_reason}

This means the system cannot produce a reliable, grounded answer.

**What to try:**
- Rephrase the question with more specific terms
- Expand the search depth setting
- Try a different topic with more available sources
"""
    
    def _build_citation_map(self, state: AgentState) -> Dict[str, Dict[str, str]]:
        """Map chunk IDs to citation numbers."""
        citations = {}
        counter = 1
        
        for result in state.search_results:
            for chunk in result.chunks:
                if chunk.chunk_id not in citations:
                    citations[chunk.chunk_id] = {
                        "num": counter,
                        "title": chunk.metadata.source_title or "Source",
                        "url": chunk.metadata.source_url
                    }
                    counter += 1
        
        for chunk in state.rag_chunks:
            if chunk.chunk_id not in citations:
                citations[chunk.chunk_id] = {
                    "num": counter,
                    "title": chunk.metadata.source_title or "Source",
                    "url": chunk.metadata.source_url
                }
                counter += 1
        
        return citations
    
    def _store_to_memory(self, state: AgentState, report: str):
        """Store chunks and report summary to Qdrant."""
        try:
            # Store all chunks
            all_chunks = []
            for result in state.search_results:
                all_chunks.extend(result.chunks)
            all_chunks.extend(state.rag_chunks)
            
            if all_chunks:
                texts = [c.text for c in all_chunks]
                embeddings = self.embedder.encode(texts).tolist()
                qdrant_store.store_chunks(all_chunks, embeddings, state.run_id)
            
            # Store report executive summary
            summary = report.split("## Executive Summary")[1].split("##")[0].strip() if "## Executive Summary" in report else report[:500]
            summary_embedding = self.embedder.encode([summary]).tolist()[0]
            
            # Store as a special "report" point
            from qdrant_client.models import PointStruct
            qdrant_store.client.upsert(
                collection_name=qdrant_store.collection_name,
                points=[PointStruct(
                    id=f"report_{state.run_id}",
                    vector=summary_embedding,
                    payload={
                        "text": summary,
                        "question": state.research_question,
                        "run_id": state.run_id,
                        "quality_score": state.critique.quality_score if state.critique else 0.0,
                        "type": "report_summary"
                    }
                )]
            )
            
        except Exception as e:
            print(f"Memory storage warning: {e}")